import sigopt.Connection

conn = Connection('<YOUR API TOKEN HERE>');

% Create your experiment
experiment = conn.experiments().create(struct( ...
  'name', 'Franke Optimization (MATLAB)', ...
  'parameters', [ ...
    struct( ...
      'name', 'x', ...
      'type', 'double', ...
      'bounds', struct( ...
        'min', 0, ...
        'max', 1 ...
      ) ...
    ), ...
    struct( ...
      'name', 'y', ...
      'type', 'double', ...
      'bounds', struct( ...
        'min', 0, ...
        'max', 1 ...
      ) ...
    ) ...
  ], ...
  'observation_budget', 30 ...
))
experiment_id = experiment.id;

% Begin the optimization loop
for n = 1:experiment.observation_budget
  % Receive a suggestion
  suggestion = conn.experiments(experiment_id).suggestions().create()
  % Evaluate your metric
  assignments = suggestion.assignments;
  value = objective_function(assignments.x, assignments.y)
  % Report an observation
  observation = conn.experiments(experiment_id).observations().create(struct( ...
    'suggestion', suggestion.id, ...
    'value', value ...
  ))
end
